--- 
abstract: Create XSPEC FITS Table Models
author: 
  - The Smithsonian Astrophysical Observatory
build_requires: 
  File::Compare: 0
  File::Spec::Functions: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: gpl3
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Astro-XSPEC-TableModel
no_index: 
  directory: 
    - inc
    - t
requires: 
  Astro::FITS::CFITSIO: 0
  Astro::FITS::CFITSIO::CheckStatus: 0
  Astro::FITS::Header: 0
  List::Util: 0
  Params::Validate: 0
  perl: 5.8.0
version: 0.01
